package com.visionary_ventures.inventoryvision.navigation

const val ROUTE_SPLASH="Splash"
const val ROUTE_KPIPAGE="Kpi Page"
const val ROUTE_KPICARD="Kpi Card"
const val ROUTE_KPIOVERVIEW="Kpi Overview"
const val ROUTE_LAYOUTPAGE="Layout Page"
const val ROUTE_LAYOUTSCREEN="Layout Screen"
const val Route_CONSTANTS="Library Constants"
const val ROUTE_FIREBASE="Library Firebase"
const val ROUTE_PRODUCTFORM="Product Form"
const val ROUTE_PRODUCTPAGE="Product Page"
const val ROUTE_PRODUCTTABLE="Product Table"
const val ROUTE_PROFILE="Profile Page"
const val ROUTE_SETTINGS="Settings Page"
const val ROUTE_TRACKER="Inventory Tracker"
const val ROUTE_GENERATOR="Report Generator"
const val ROUTE_TOOLS="Tools Page"
const val ROUTE_WALLET="Wallets Page"
